routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::name('home')->get('/', 'HomeController@home');

Route::name ('statPlayers')->get('/statPlayers', 'StatController@statPlayers');

Route::name('general')->get('classement/{platform}', 'ClassementController@general');
Route::name('classementApi')->get('classementApi/{platform}/text', 'ClassementController@generalText');
Route::name('classementApi')->get('classementApi/{platform}/discord', 'ClassementController@generalDiscord');

Route::view('/faq', 'faq')->name('faq');

Route::name('language')->get('language/{lang}', 'UserController@language');

//Route::name('annoncement')->get('annoncement', 'MailController@annoncement');

Route::resource('user', 'UserController', [
    'only' => ['show']
]);

Route::resource('video', 'VideoController', [
    'only' => ['index']
]);

Route::name('videoLast')->get('videoLast', 'VideoController@lastVideo');

Route::middleware('auth')->group(function () {

    Route::resource('user', 'UserController', [
        'only' => ['edit', 'update']
    ]);

    Route::view('/research', 'matchmaking.research')->name('research');

    Route::resource('video', 'VideoController', [
        'only' => ['store', 'destroy']
    ]);

    Route::name('videoEdit')->get('videoEdit/{user}', 'VideoController@videoEdit');

    Route::name('videoLike')->get('videolike/{video}', 'VideoController@like');

    Route::name ('researchMatchmaking')->get ('researchMatchmaking/{user}/{iter}', 'MatchmakingController@researchMaking');

    Route::name ('displayMatch')->get ('displayMatch/{user_main}/{user_adv}/{match}/{msg}', 'MatchmakingController@displayMatch');

    Route::name ('validateMatch')->get('validateMatch/{user}/{match}/{result}', 'MatchmakingController@validateMatch');

    Route::middleware('ajax')->group(function () {
        Route::post('images-save', 'UploadImagesController@store')->name('save-images');
        Route::delete('images-delete', 'UploadImagesController@destroy')->name('destroy-images');
        Route::get('images-server','UploadImagesController@getServerImages')->name('server-images');
    });

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'bio', 'plateforme_name', 'plateforme', 'points'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function dispo()
    {
        return $this->hasOne(DisponiblePlayer::class);
    }

    public function resultats()
    {
        return $this->hasMany(Resultat::class);
    }

    public function videos()
    {
        return $this->hasMany(Video::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\Resultat;
use Illuminate\Http\Request;
use App\Models\User;
use DB;
use Illuminate\Support\Facades\Config;

class UserController extends Controller
{

    public function show(User $user)
    {
        $id_user = $user->id;

        $result = DB::select(
            DB::raw("SELECT rank FROM (
                                        SELECT @rn:=@rn+1 AS rank, id, points, plateforme
                                        FROM (
                                          SELECT id, points, plateforme
                                          FROM users
                                          where plateforme = :plateforme1
                                          ORDER BY points DESC
                                        ) t1, (SELECT @rn:=0) t2) ranking
                                        WHERE id = :id_user
                                        AND plateforme = :plateforme2;"),
            [
                'id_user' => $id_user,
                'plateforme1' => $user->plateforme,
                'plateforme2' => $user->plateforme,
            ]
    );

        $user->rank_classement = $result[0]->rank;
        $user->total_player = User::query()
            ->where('plateforme', '=', $user->plateforme)
            ->count();

        $all_matchs = [];

        $resultats = $user->resultats()
            ->orderBy('id', 'desc')
            ->limit(10)
            ->get();

        foreach ($resultats as &$resultat){

            $match_array = [];

            $match_adv = $resultat->match()->get();
            $resultat_adv = $match_adv[0]->resultats()
                ->where('user_id', '!=', $id_user)
                ->get();

            if($resultat->resultat == 1){
                $match_result = __('Victoire');
            }elseif ($resultat->resultat == 0 && !is_null($resultat->resultat)){
                $match_result = __('Défaite');
            }elseif ($resultat->resultat == 2){
                $match_result = __('Égalité');
            }else{
                $match_result = __('En cours');
            }

            $adversary = $resultat_adv[0]->user()->get();

            $match_array['result_int'] = $resultat->resultat;
            $match_array['result'] = $match_result;
            $match_array['adversary'] = $adversary[0]->plateforme_name;
            $match_array['map'] = __(Config::get('constants.circuits')[$match_adv[0]->map]);
            $match_array['date'] = $match_adv[0]->created_at->format('d/m/Y');

            $all_matchs[] = $match_array;
        }

        $videos = $user->videos()->get();

        foreach ($videos as &$video){
            $pos = strpos($video->url, '=') + 1;
            $id = substr($video->url, $pos);
            $video->video_url = 'https://www.youtube.com/embed/' . $id  . '?controls=0';
        }

        return view('user.index', compact('user', 'all_matchs', 'videos'));
    }

    public function edit(User $user)
    {
        $this->authorize('manage', $user);
        $videos = $user->videos()->get();
        return view('user.edit', compact('user', 'videos'));
    }

    public function update(UserRequest $request, User $user)
    {
        $user->bio = $request->bio;
        $user->update($request->all());
        return redirect()->route('user.edit', $user->id)->with('ok', __("L'utilisateur a bien été modifié"));
    }

    public function language(String $locale)
    {
        $locale = in_array($locale, config('app.locales')) ? $locale : config('app.fallback_locale');
        session(['locale' => $locale]);
        return back();
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('ok'))
            <div class="alert alert-dismissible alert-success fade show" role="alert">
                {{ session('ok') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        @if (session('error'))
            <div class="alert alert-dismissible alert-danger fade show" role="alert">
                {{ session('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        @if(!empty($errors->first()))
            <div class="alert alert-danger alert-dismissible fade show">
                <span>{{ $errors->first() }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-10 mb-3">
                <div class="card">
                    <div class="card-header">{{ __('Informations profil') }}</div>
                    <div class="card-body">

                        <ul class="nav nav-tabs" id="UserTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="user-tab" data-toggle="tab" href="#user" role="tab" aria-controls="user" aria-selected="true">Profil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="avatar-tab" data-toggle="tab" href="#avatar" role="tab" aria-controls="videos" aria-selected="false">Avatar</a>
                            </li>
                        </ul>

                        <br/>

                        <div class="tab-content" id="UserTabContent">

                            <div class="tab-pane fade show active" id="user" role="tabpanel" aria-labelledby="user">

                                <form method="POST" action="{{ route('user.update', $user->id) }}">
                                    {{ csrf_field() }}
                                    {{ method_field('PUT') }}

                                    <div class="form-group row">
                                        <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Adresse Mail') }}</label>

                                        <div class="col-md-6">
                                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ Auth::user()->email }}" required autocomplete="email">

                                            @error('email')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Pseudo') }}</label>

                                        <div class="col-md-6">
                                            <input id="name" type="text" class="form-control" name="name" value="{{ Auth::user()->name }}" required>
                                        </div>
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>

                                    <div class="form-group row">
                                        <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Plateforme de jeu') }}</label>
                                        <select class="col-md-6 custom-select" id="plateforme" name="plateforme">
                                            <option value="{{ Auth::user()->plateforme }}">{{ Auth::user()->plateforme }}</option>
                                            <option value="Playstation 4">Playstation 4</option>
                                            <option value="Xbox One">Xbox One</option>
                                            <option value="Switch">Switch</option>
                                        </select>
                                        @error('plateforme')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>

                                    <div class="form-group row">
                                        <label for="plateforme_name" class="col-md-4 col-form-label text-md-right">{{ __('Nom de joueur sur la plateforme') }}</label>

                                        <div class="col-md-6">
                                            <input id="plateforme_name" type="text" class="form-control" name="plateforme_name" value="{{ Auth::user()->plateforme_name }}" required>
                                        </div>
                                        @error('plateforme_name')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>

                                    <div class="form-group row">
                                        <label for="bio" class="col-md-4 col-form-label text-md-right">{{ __('Biographie') }}</label>

                                        <div class="col-md-6">
                                            <textarea id="bio" type="textArea" class="form-control" name="bio" value="{{ Auth::user()->bio }}">{{ Auth::user()->bio }}</textarea>
                                        </div>
                                        @error('bio')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-6 offset-md-4">
                                            <button type="submit" class="btn btn-primary">
                                                {{ __('Modifier') }}
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                            <div class="tab-pane fade" id="avatar" role="tabpanel" aria-labelledby="avatar-tab">

                                <div class="form-group">
                                    <label>{{ __('Modification de votre avatar') }}</label>
                                    <form method="post" action="{{ route('save-images') }}" enctype="multipart/form-data" class="dropzone" id="my-dropzone">
                                        @csrf
                                        <div class="dz-message">
                                            <div class="col-xs-8">
                                                <div class="message">
                                                    <p>{{ __('Déposez votre avatar ici ou cliquez') }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div id="preview" style="display: none;">
                                    <div class="dz-preview dz-file-preview">
                                        <div class="dz-image"><img data-dz-thumbnail /></div>
                                        <div class="dz-details">
                                            <div class="dz-size"><span data-dz-size></span></div>
                                            <div class="dz-filename"><span data-dz-name></span></div>
                                        </div>
                                        <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div>
                                        <div class="dz-error-message"><span data-dz-errormessage></span></div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>

        $('a.form-delete').click((e) => {
            e.preventDefault();
            let href = $(e.currentTarget).attr('href')
            Swal.fire({
                title: '@lang('Vraiment supprimer cette vidéo ?')',
                type: 'error',
                showCancelButton: true,
                confirmButtonColor: '#DD6B55',
                confirmButtonText: '@lang('Oui')',
                cancelButtonText: '@lang('Non')'
            }).then((result) => {
                if (result.value) {
                    $("form[action='" + href + "'").submit()
                }
            })
        });

        Dropzone.options.myDropzone = {
            uploadMultiple: false,
            parallelUploads: 1,
            maxFilesize: 3,
            maxFiles: 1,
            previewTemplate: document.querySelector('#preview').innerHTML,
            addRemoveLinks: true,
            acceptedFiles: 'image/*',
            dictInvalidFileType : '{{ __('Type de fichier interdit') }}',
            dictRemoveFile: '{{ __('Supprimer') }}',
            dictFileTooBig: "{{ __("L'image fait plus de 3 Mo") }}",
            timeout: 10000,
            init () {
                const myDropzone = this;
                $.get('{{ route('server-images') }}', data => {
                    $.each(data.image, (key, value) => {
                        const mockFile = {
                            name: value.original,
                            size: value.size,
                            dataURL: '{{ url('avatars') }}' + '/' + value.server
                        };
                        myDropzone.files.push(mockFile);
                        myDropzone.emit("addedfile", mockFile);
                        myDropzone.createThumbnailFromUrl(mockFile,
                            myDropzone.options.thumbnailWidth,
                            myDropzone.options.thumbnailHeight,
                            myDropzone.options.thumbnailMethod, true, (thumbnail) => {
                                myDropzone.emit('thumbnail', mockFile, thumbnail);
                            });
                        myDropzone.emit('complete', mockFile);
                    });
                });
                this.on('addedfile', function(file) {
                    if (myDropzone.files.length > 1) {
                        myDropzone.removeFile(myDropzone.files[0]);
                    }
                });
                this.on("removedfile", file => {
                    $.ajax({
                        method: 'delete',
                        url: '{{ route('destroy-images') }}',
                        data: { name: file.name, _token: $('[name="_token"]').val() }
                    });
                });
            }
        };
    </script>
@endsection

resources/views/user/video.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('ok'))
            <div class="alert alert-dismissible alert-success fade show" role="alert">
                {{ session('ok') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        @if (session('error'))
            <div class="alert alert-dismissible alert-danger fade show" role="alert">
                {{ session('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        @if(!empty($errors->first()))
            <div class="alert alert-danger alert-dismissible fade show">
                <span>{{ $errors->first() }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-10 mb-3">
                <div class="card">
                    <div class="card-header">{{ __('Gérer mes vidéos') }}</div>
                    <div class="card-body">

                        <h5>{{ __("Vos 3 meilleurs courses en video YouTube :") }}</h5>

                        <form method="POST" action="{{ route('video.store', $user->id) }}">
                            {{ csrf_field() }}

                            <div class="form-group row">
                                <label for="video" class="col-md-4 col-form-label text-md-right">{{ __('URL de la video') }}</label>
                                <div class="col-md-6">
                                    <input id="video" type="text" class="form-control" name="video" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Courte description') }}</label>
                                <div class="col-md-6">
                                    <input id="description" type="text" class="form-control" name="description" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-7  text-md-right">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Ajouter la video') }}
                                    </button>
                                </div>
                            </div>
                        </form>

                        <hr/>

                        <div class="table-responsive">
                            <table class="table">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">{{ __('Vos meilleurs courses') }}</th>
                                    <th scope="col">{{ __('Lien') }}</th>
                                    <th scope="col">{{ __('Like') }}</th>
                                    <th scope="col">{{ __('Suppression') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($videos as $video)
                                    <tr>
                                        <th scope="row">
                                            {{ $video->description }}
                                        </th>
                                        <td>
                                            <a href="{{ $video->url }}"><i class="fab fa-youtube"></i></a>
                                        </td>
                                        <td>
                                            {{ $video->like }}
                                        </td>
                                        <td>
                                            <a class="form-delete text-danger" href="{{ route('video.destroy', $video->id) }}">
                                                <i class="fas fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <form action="{{ route('video.destroy', $video->id) }}" method="POST" class="hide">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>
        $('a.form-delete').click((e) => {
            e.preventDefault();
            let href = $(e.currentTarget).attr('href')
            Swal.fire({
                title: '@lang('Vraiment supprimer cette vidéo ?')',
                type: 'error',
                showCancelButton: true,
                confirmButtonColor: '#DD6B55',
                confirmButtonText: '@lang('Oui')',
                cancelButtonText: '@lang('Non')'
            }).then((result) => {
                if (result.value) {
                    $("form[action='" + href + "'").submit()
                }
            })
        });
    </script>
@endsection